modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="mcalecs"
version="0.4"
displayName="McAlec's Mod"
updateJSONURL="https://raw.githubusercontent.com/McAlec1/mcalecsmod/master/update.json"
displayURL="https://modrinth.com/mod/mcalecs-mod"
logoFile="logo.png"
credits="McAlec and all other assets go to the orginal creators."
authors="McAlec"
description="..."

[[dependencies.mcalecs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




