modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="mcalecs"
version="0.6"
displayName="McAlec's Mod"
updateJSONURL="https://raw.githubusercontent.com/McAlec1/mcalecsmod/master/update.json"
displayURL="https://modrinth.com/mod/mcalecs-mod"
logoFile="logo.png"
credits="McAlec. I do not own/claim any music, pictures, items, or textures that may be deemed to be mine. I own all the assets I have created."
authors="McAlec"
description="Soon..."

[[dependencies.mcalecs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.mcalecs]]
    modId="configured"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mcalecs]]
    modId="forgeconfigapiport"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mcalecs]]
    modId="forgeconfigscreens"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mcalecs]]
    modId="catalogue"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

