modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="mcalecsmod"
version="0.2"
displayName="McAlecs Mod"
displayURL="https://modrinth.com/mod/mcalecs-mod"
logoFile="logo.png"
credits="McAlec and all other assets go to the orginal creators."
authors="McAlec"
description="..."

[[dependencies.mcalecsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




